# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-20 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='instruments',
        ),
        migrations.AddField(
            model_name='song',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='requiredInstruments',
            field=models.TextField(blank=True, choices=[(b'Piano', b'Piano')], max_length=10000),
        ),
    ]
