# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180301_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='track',
            name='sound',
            field=models.FileField(upload_to=b'Musix/Musix/tracks/1'),
        ),
    ]
