# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180305_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='sound',
            field=models.FileField(upload_to=b'Musix/Musix/tracks/1'),
        ),
    ]
