# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180305_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='sound',
            field=models.FileField(upload_to=b'1'),
        ),
    ]
