# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180306_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='creator',
        ),
        migrations.AlterField(
            model_name='song',
            name='requiredInstruments',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
