# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180306_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='additionalInstruments',
            field=models.BooleanField(choices=[(b'Y', b'Yes'), (b'N', b'No')]),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='song',
            name='requiredInstruments',
            field=models.TextField(blank=True, choices=[(b'AcGuitar', b'Acoustic guitar'), (b'Bass', b'Bass'), (b'Cello', b'Cello'), (b'Clarinet', b'Clarinet'), (b'Drums', b'Drums'), (b'ElecGuitar', b'Electric guitar'), (b'Flute', b'Flute'), (b'Harm', b'Harmonica'), (b'Organ', b'Organ'), (b'Piano', b'Piano'), (b'Sax', b'Saxophone'), (b'Synth', b'Synth'), (b'Trombone', b'Trombone'), (b'Trumpet', b'Trumpet'), (b'Violin', b'Violin'), (b'Xylo', b'Xylophone')], max_length=10000),
        ),
        migrations.AlterField(
            model_name='track',
            name='instrument',
            field=models.CharField(choices=[(b'AcGuitar', b'Acoustic guitar'), (b'Bass', b'Bass'), (b'Cello', b'Cello'), (b'Clarinet', b'Clarinet'), (b'Drums', b'Drums'), (b'ElecGuitar', b'Electric guitar'), (b'Flute', b'Flute'), (b'Harm', b'Harmonica'), (b'Organ', b'Organ'), (b'Piano', b'Piano'), (b'Sax', b'Saxophone'), (b'Synth', b'Synth'), (b'Trombone', b'Trombone'), (b'Trumpet', b'Trumpet'), (b'Violin', b'Violin'), (b'Xylo', b'Xylophone')], max_length=100),
        ),
    ]
