# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180314_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='requiredInstruments',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
