# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180314_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='additionalInstruments',
            field=models.CharField(choices=[(b'Y', b'Yes'), (b'N', b'No')], max_length=5),
        ),
    ]
