# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20180314_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='finished',
        ),
    ]
