# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20180315_1322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Musician',
        ),
    ]
