from .ban import *
from .index import *
from .instrument import *
from .login import *
from .musician import *
from .premium import *
from .profile import *
from .registration import *
from .report import *
from .song import *
from .track import *
